#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=../slurm_output/slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2
source activate DL2

cd $HOME/Logic-LLM/


python models/logic_program.py \
    --api_key "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" \
    --dataset_name "LTL" \
    --framework "huggingface" \
    --split dev \
    --model_name "meta-llama/Meta-Llama-3-8B" \
    --save_path "./outputs/testing" \
    --max_new_tokens 1024 \